import type { Metadata } from 'next' 
import '@/app/globals.css'
import { Poppins } from 'next/font/google'
import Header from '@/components/Header'
 
const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '700'], 
})
export const metadata: Metadata = {
  title: 'Felipe Gomes Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body> 
        <Header />
        {children}
      </body>
    </html>
  )
}
